# Generated by Django 5.2.2 on 2025-06-23 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_siteimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
